AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'aws-tempest-alexa-demo

  Sample SAM Template for aws-tempest-alexa-demo

  '
Mappings:
  Variables:
    AlexaSkillKit:
      Id: amzn1.ask.skill.5b2ae4ab-5f1d-4d26-8ccc-c7302fb7d9c8
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs8.10
    Environment:
      Variables:
        DEVICE_TABLE:
          Ref: DeviceTable
Resources:
  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://werberm-sandbox/2472f96f6c4542f37431c710bdfefa3e
      Handler: app.handler
  CreateThingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://werberm-sandbox/35a92d29aa4abde876d62a6ed246f825
      Handler: app.handler
      Policies:
      - Statement:
        - Sid: IoTCreateThingPolicy
          Effect: Allow
          Action:
          - iot:CreateThing
          - iot:DescribeThing
          - iot:UpdateThing
          Resource: '*'
  AssociateThingToUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://werberm-sandbox/ffcbe85a1bba0ae1f31c2825ec894875
      Handler: app.handler
      Policies:
      - Statement:
        - Sid: DynamoDBCrudPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          Resource:
          - Fn::GetAtt:
            - DeviceTable
            - Arn
          - Fn::Sub: ${DeviceTable.Arn}/index/*
  CreateDeviceTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://werberm-sandbox/cdf0917d10b5ceb65b063e49e09d03fb
      Handler: app.handler
      Policies:
      - Statement:
        - Sid: DynamoDBCrudPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          Resource:
          - Fn::GetAtt:
            - DeviceTable
            - Arn
          - Fn::Sub: ${DeviceTable.Arn}/index/*
  GetDevicesByUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://werberm-sandbox/7a35272f494c6d860a65d3f7b89f84bf
      Handler: app.handler
      Policies:
      - Statement:
        - Sid: DynamoDBReadPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          Resource:
          - Fn::GetAtt:
            - DeviceTable
            - Arn
          - Fn::Sub: ${DeviceTable.Arn}/index/*
  AlexaSkillFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn: AlexaSkillFunction
    Properties:
      Action: lambda:InvokeFunction
      EventSourceToken:
        Fn::FindInMap:
        - Variables
        - AlexaSkillKit
        - Id
      FunctionName:
        Fn::GetAtt:
        - AlexaSkillFunction
        - Arn
      Principal: alexa-connectedhome.amazon.com
  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: hashId
        AttributeType: S
      - AttributeName: sortId
        AttributeType: S
      KeySchema:
      - AttributeName: hashId
        KeyType: HASH
      - AttributeName: sortId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  AlexaSkillFunction:
    Description: Alexa Skill Lambda Function ARN
    Value:
      Fn::GetAtt:
      - AlexaSkillFunction
      - Arn
  AlexaSkillFunctionIamRole:
    Description: Implicit IAM Role created for Alexa Skill function
    Value:
      Fn::GetAtt:
      - AlexaSkillFunctionRole
      - Arn
